# k3d configuration file
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: feature-flag-all-the-things
servers: 3
agents: 5
kubeAPI:
  host: cluster.test
  hostIP: 127.0.0.1
  hostPort: "6445"
# k3d defaults to 1.20? whyyy
image: rancher/k3s:v1.31.1-k3s1
ports:
  - port: 50080:80
    nodeFilters:
      - loadbalancer
  - port: 50443:443
    nodeFilters:
      - loadbalancer
files:
  - description: "argo-cd helm chart"
    source: ./manifests/argo-cd-helm.yaml
    destination: k3s-manifests-custom/argo-cd-helm.yaml
registries:
  create:
    name: registry.test
    host: "0.0.0.0"
    hostPort: "50050"
    volumes:
      # k3d expands environment variables so this works as expected
      - $PWD/registry/cluster:/var/lib/registry # persist registry data locally
  config: |
    configs:
      "registry-1.docker.io":
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKER_PASSWORD"
options:
  k3s:
    nodeLabels:
      # TODO: split the nodes into 2-3 groups with labels and then split the agents into two groups
      - label: foo=bar # same as `--k3s-node-label 'foo=bar@agent:1'` -> this results in a Kubernetes node label
        nodeFilters:
          - agent:1
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
