opentelemetry-demo:
  components:
    frontend:
      envOverrides:
        - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://otel-demo-collector.dev:50080/otlp-http/v1/traces
    frontendProxy:
      ingress:
        enabled: true
        annotations: {}
        hosts:
          - host: otel-demo.dev
            paths:
              - path: /
                pathType: Prefix
                port: 8080
  opentelemetry-collector:
    mode: daemonset
    service:
      # v-- There's a bug in the chart which causes this to throw a comparison error if not set explicitly
      internalTrafficPolicy: "Local"

    image:
      repository: "otel/opentelemetry-collector-contrib"

    command:
      name: "otelcol-contrib"

    ingress:
      enabled: true
      hosts:
        - host: otel-demo-collector.dev
          paths:
            - path: /
              pathType: Prefix
              port: 4318

    presets:
      logsCollection:
        enabled: true
      kubernetesAttributes:
        enabled: true
      kubeletMetrics:
        enabled: true
      hostMetrics:
        enabled: true
